force-app/main/default/objects/Target_Acknowledgement__c/Target_Acknowledgement__c.object-meta.xml
<CustomObject>
    <label>Target Acknowledgement</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Target Acknowlegement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Acknowledgements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Acknowledgement__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Acknowledgements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Acknowledgement__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Acknowledgements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Acknowledgement__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Acknowledgement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not yet started</fullName>
                <default>true</default>
                <label>Not yet started</label>
            </value>
            <value>
                <fullName>Not yet Acknowledged</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Reverted</fullName>
            </value>
            <value>
                <fullName>Target sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Acknowledgement_History__c/Target_Acknowledgement_History__c.object-meta.xml
<CustomObject>
    <label>Target Acknowledgement History</label>
    <nameField>
        <displayFormat>TCH-{0000}</displayFormat>
        <label>Target Acknowledgement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Acknowledgement Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Acknowledgement_History__c/fields/Target_Acknowledgement__c.field-meta.xml
<CustomField>
    <fullName>Target_Acknowledgement__c</fullName>
    <label>Target Acknowledgement</label>
    <referenceTo>Target_Acknowledgement__c</referenceTo>
    <relationshipLabel>Target Acknowledgement Histories</relationshipLabel>
    <relationshipName>Target_Acknowledgement_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/Target_Distribution__c.object-meta.xml
<CustomObject>
    <label>Target Distribution</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>TD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Distribution__c/fields/Allocated_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Percentage__c</fullName>
    <label>Allocated Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDD_Target_Distribustions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDM_Target_Distribustions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateBDMTargetsBatch.cls
public class UpdateBDMTargetsBatch implements Database.Batchable<sObject>, Database.Stateful {
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id, BDD__c, BDM__c, Financial_Year__c, Allocated_Percentage__c, CurrencyIsoCode FROM Target_Distribution__c WHERE BDD__c = \'' + currentUser + '\' AND financial_Year__c = \'' + financialYear + '\'');  
    }
    
    public void execute(Database.BatchableContext context, List<Target_Distribution__c> scope) {
        Map<Id, Target_Distribution__c> BDMTargetDistMap = new Map<Id, Target_Distribution__c>();
        for(Target_Distribution__c record : scope){
            Id bdmValue = (Id)record.get('BDM__c');
            BDMTargetDistMap.put(bdmValue, record);
        }
        
        BDDController.updateBDMTargets(currentUser, financialYear, bddTarget, BDMTargetDistMap, currencyVal);
    }
    
    public void finish(Database.BatchableContext context) {  
        List<Target_Acknowledgement__c> tAcknowledgeList = new List<Target_Acknowledgement__c>();
        Map<Id, Target_Acknowledgement__c> existingRecordsMap = new Map<Id, Target_Acknowledgement__c>();
        List<Target_Acknowledgement_History__c> ackHistoryList = new List<Target_Acknowledgement_History__c>();
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        User usr = [SELECT Id, Name, Email from User WHERE Id = : currentUser];
        //EmailTemplate et = [SELECT Id, subject, HtmlValue FROM EmailTemplate WHERE DeveloperName =: 'BDD_Target_Message'];
     
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] { usr.Email };
       
        String body = 'Hi ' + usr.Name + ' , <br/><br/>';    
        body += 'Sales Target has been set for the ' + financialYear + ' successfully. Kindly review ' + financialYear + ' sales target.  <br/><br/>' ;
        body += 'Thank You. <br/>';
        body += 'Gibson Brands. <br/>';


        mail.setToAddresses(toAddresses);
        // mail.setTemplateId(et.Id);
        mail.setSubject('Sales Target Set Successfully - ' +financialYear);
        mail.setHTMLBody(body);
        mailList.add(mail);
        if(!mailList.isEmpty()){
            Messaging.sendEmail(mailList);
        }
        
        for (Target_Acknowledgement__c tAcknowledge : [SELECT Id, BDD__c, BDM__c, Status__c, Financial_Year__c,Comments__c FROM Target_Acknowledgement__c WHERE BDD__c = :currentUser AND BDM__c IN :bdmList AND Financial_Year__c = :financialYear]) {
            existingRecordsMap.put(tAcknowledge.BDM__c, tAcknowledge);
        }
        
        if(isAcknowledge){
            for(Id bdmId : bdmList){
                if (existingRecordsMap.containsKey(bdmId)) {
                    Target_Acknowledgement__c existingRecord = existingRecordsMap.get(bdmId);
                    existingRecord.Status__c = 'Target sent';
                    existingRecord.Comments__c = '';
                    tAcknowledgeList.add(existingRecord);
                } else {
                    Target_Acknowledgement__c newRecord = new Target_Acknowledgement__c();
                    newRecord.BDD__c = currentUser;
                    newRecord.BDM__c = bdmId;
                    newRecord.Status__c = 'Target sent';
                    newRecord.Financial_Year__c = financialYear;
                    newRecord.Comments__c = '';
                    tAcknowledgeList.add(newRecord);
                }
            }
        }
        if(!tAcknowledgeList.isEmpty()){
            Upsert tAcknowledgeList;
            for(Target_Acknowledgement__c tAcknowledge : tAcknowledgeList){
                Target_Acknowledgement_History__c newHistory = new Target_Acknowledgement_History__c();
                newHistory.Target_Acknowledgement__c = tAcknowledge.Id;
                newHistory.Status__c = tAcknowledge.Status__c;
                newHistory.Comments__c = tAcknowledge.Comments__c;
                ackHistoryList.add(newHistory);
            }
        }
        if(!ackHistoryList.isEmpty()){
            Insert ackHistoryList;
        }
    }
    
    private Id currentUser;
    private String financialYear;
    private decimal bddTarget;
    Private Map<Id, Target_Distribution__c> BDMTargetDistMap;
    Private string currencyVal; 
    Private Boolean isAcknowledge;
    Private List<string> bdmList;
    
    public UpdateBDMTargetsBatch(Id currentUser, String financialYear, Decimal BDDTarget, Map<Id, Target_Distribution__c> BDMTargetDistMap, String currencyVal,Boolean isAcknowledge,List<String> bdmList) {
        this.currentUser = currentUser;
        this.financialYear = financialYear;
        this.bddTarget = bddTarget;
        this.BDMTargetDistMap = BDMTargetDistMap;
        this.currencyVal = currencyVal;
        this.isAcknowledge = isAcknowledge;
        this.bdmList = bdmList;
    }
}