force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Unit__c/fields/Available_for_Target__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Target?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/Target_Config__c.object-meta.xml
<CustomObject>
    <label>Target Config</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>TC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Config__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Configs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Target Configs</relationshipLabel>
    <relationshipName>BU_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDD</fullName>
            </value>
            <value>
                <fullName>BDM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Variance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Variance_Amount__c</fullName>
    <formula>Target__c - Overall_Actuals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BDMAccountSummaryController.cls
public class BDMAccountSummaryController {
    
    @AuraEnabled(Cacheable = true)
    public static Map<String, Map<String, Decimal>> getTargetBDM(String financialYear,Id accountId,Id currentUser) {
        Set<String> monthSet = new Set<String>{'Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'};
            Map<String, Map<String, Decimal>> busUnitMonthSalesTarMap = new Map<String, Map<String, Decimal>>();
        
        for(Business_Unit__c busUnit : [select id,name from Business_Unit__c where Available_for_Target__c = true]) {
            Map<String, Decimal> monthSalesTarMap = new Map<String, Decimal>();
            for(String month : monthSet) {
                monthSalesTarMap.put(month, 0); 
            }
            busUnitMonthSalesTarMap.put(busUnit.name, monthSalesTarMap);
        }        
        getTargetValues(financialYear, accountId, currentUser, busUnitMonthSalesTarMap);
        System.debug('BDM Id'+busUnitMonthSalesTarMap);
        
        return busUnitMonthSalesTarMap;
    }
    
    private static void getTargetValues(String financialYear,Id accountId,Id selectedUser, Map<String, Map<String, Decimal>> busUnitMonthSalesTarMap) {
        
        for(
            AggregateResult aggr : 
            [select Business_Unit__r.Name, Month__c, SUM(Target__c) from Target_Config__c 
             where Business_Unit__c != null AND Level__c ='BDM' AND Business_Unit__r.Available_for_Target__c = true AND Account__c =: accountId AND BDM__c =: selectedUser AND Financial_Year__c =: financialYear
             group by Business_Unit__r.Name, Month__c]
        ) { 
            Decimal target = (Decimal) aggr.get('expr0');
            
            busUnitMonthSalesTarMap.get(
                (String) aggr.get('Name')
            ).put(
                (String) aggr.get('Month__c'), target
            );
        }
    }
    
    @AuraEnabled(Cacheable = true)
    public static Map<String, Map<String, Decimal>> getActualsBDM(String financialYear,Id accountId,Id currentUser) {
        Set<String> monthSet = new Set<String>{'Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'};
            Map<String, Map<String, Decimal>> busUnitMonthSalesTarMap = new Map<String, Map<String, Decimal>>();
        
        for(Business_Unit__c busUnit : [select id,name from Business_Unit__c where Available_for_Target__c = True]) {
            Map<String, Decimal> monthSalesTarMap = new Map<String, Decimal>();
            for(String month : monthSet) {
                monthSalesTarMap.put(month, 0); 
            }
            busUnitMonthSalesTarMap.put(busUnit.name, monthSalesTarMap);
        }
        
        getActualValues(financialYear, accountId, currentUser, busUnitMonthSalesTarMap);
        System.debug('BDM Id'+busUnitMonthSalesTarMap);
        
        return busUnitMonthSalesTarMap;
    }
    
    private static void getActualValues(String financialYear,Id accountId,Id selectedUser, Map<String, Map<String, Decimal>> busUnitMonthSalesTarMap) {
        
        for(
            AggregateResult aggr : 
            [select Business_Unit__r.Name, Month__c, SUM(Actual_Amount__c) from Actuals__c 
             where Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND Account__c =: accountId AND BDM__c =: selectedUser AND Financial_Year__c =: financialYear
             group by Business_Unit__r.Name, Month__c]
        ) { 
            Decimal target = (Decimal) aggr.get('expr0');
            
            busUnitMonthSalesTarMap.get(
                (String) aggr.get('Name')
            ).put(
                (String) aggr.get('Month__c'), target
            );
        }
    }
    
    @AuraEnabled(Cacheable = true)
    public static Map<String, Map<String, Decimal>> getVarianceBDM(String financialYear,Id accountId,Id currentUser) {
        Set<String> monthSet = new Set<String>{'Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'};
            Map<String, Map<String, Decimal>> busUnitMonthSalesTarMap = new Map<String, Map<String, Decimal>>();
        
        for(Business_Unit__c busUnit : [select id,name from Business_Unit__c where Available_for_Target__c = True]) {
            Map<String, Decimal> monthSalesTarMap = new Map<String, Decimal>();
            for(String month : monthSet) {
                monthSalesTarMap.put(month, 0); 
            }
            busUnitMonthSalesTarMap.put(busUnit.name, monthSalesTarMap);
        }
        
        getVarianceValues(financialYear, accountId, currentUser, busUnitMonthSalesTarMap);
        System.debug('BDM Id'+busUnitMonthSalesTarMap);
        
        return busUnitMonthSalesTarMap;
    }
    
    private static void getVarianceValues(String financialYear,Id accountId,Id selectedUser, Map<String, Map<String, Decimal>> busUnitMonthSalesTarMap) {
        
        for(
            AggregateResult aggr : 
            [select Business_Unit__r.Name, Month__c, SUM(Variance_Amount__c) from Variance__c 
             where Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND Account__c =: accountId AND BDM__c =: selectedUser AND Financial_Year__c =: financialYear
             group by Business_Unit__r.Name, Month__c]
        ) { 
            Decimal target = (Decimal) aggr.get('expr0');
            
            busUnitMonthSalesTarMap.get(
                (String) aggr.get('Name')
            ).put(
                (String) aggr.get('Month__c'), target
            );
        }
    }
}