force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Commitment__c/Order_Commitment__c.object-meta.xml
<CustomObject>
    <label>Order Commitment</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Order Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Commitment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Commitments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/Target_Commit_Stats__c.object-meta.xml
<CustomObject>
    <label>Target Commit Stats</label>
    <nameField>
        <displayFormat>TCS-{0000}</displayFormat>
        <label>Target Commit Stats Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Commit Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Target Commit Stats</relationshipLabel>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Apr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aug</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Target Commit Stats</relationshipLabel>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Dec</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Feb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/IsUpload__c.field-meta.xml
<CustomField>
    <fullName>IsUpload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jan</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jul</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jun</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <defaultValue>0</defaultValue>
    <label>May</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nov</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Oct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Target Commit Stats</relationshipLabel>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default Data</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Unique_key__c.field-meta.xml
<CustomField>
    <fullName>Unique_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OrderCommitmentController.cls
public class OrderCommitmentController {
    
    public static void updateTargetCommitStats(List<Order_Commitment__c> orderCommitmentList) {
        Set<String> keys = new Set<String>();
        List<Sobject> targetCommitStatsToUpdate = new List<Sobject>();
        List<String> months = new List<String>{'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'};
        
        Map<String, Order_Commitment__c> orderKeyMap = new Map<String, Order_Commitment__c>();
        
        for (Order_Commitment__c orderCommitment : orderCommitmentList) {
            String key = orderCommitment.Financial_Year__c + '-' + String.valueOf(orderCommitment.BDM__c).substring(0, 15) + '-' + 
                String.valueOf(orderCommitment.Account__c).substring(0, 15) + '-' + String.valueOf(orderCommitment.Business_Unit__c).substring(0, 15) + '-' + 
                String.valueOf(orderCommitment.Product__c).substring(0, 15);
            keys.add(key);
            key += + '-' + orderCommitment.Month__c;
            orderKeyMap.put(key, orderCommitment);
        }
        System.debug('keys==>'+ keys);
        System.debug('keys size==>'+ keys.size());
        
        
        for (
            Target_Commit_Stats__c targetCommitStats :
            [SELECT Id, Unique_key__c, Jan__c, Feb__c, Mar__c, Apr__c, May__c, Jun__c, Jul__c, Aug__c, Sep__c, Oct__c, Nov__c, Dec__c, IsUpload__c, Status__c
             FROM Target_Commit_Stats__c WHERE Unique_key__c IN : keys AND IsUpload__c = false]
        ) {
            Sobject sobj = targetCommitStats;
            for (String month : months) {
                String key = targetCommitStats.Unique_key__c + '-' + month;
                
                Order_Commitment__c orderCommitment = orderKeyMap.get(key);
                
                if (orderCommitment != null) {
                    sobj.put(month + '__c', orderCommitment.Quantity__c);
                }
            }
            targetCommitStatsToUpdate.add(sobj);
        }
        
        if (!targetCommitStatsToUpdate.isEmpty()) {
           update targetCommitStatsToUpdate;
        }
    }
}