force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Unit__c/fields/Available_for_Target__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Target?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Config__c/Hierarchy_Config__c.object-meta.xml
<CustomObject>
    <label>Hierarchy Config</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>HC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hierarchy Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hierarchy_Config__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDD_Hierarchy_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Config__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDM</fullName>
            </value>
            <value>
                <fullName>BDD</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>DTC BDD</fullName>
            </value>
            <value>
                <fullName>DTC BDM</fullName>
            </value>
            <value>
                <fullName>Sales Person</fullName>
                <isActive>false</isActive>
                <label>Sales Person</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hierarchy_Config__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDM_Hierarchy_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/Order_Commitment__c.object-meta.xml
<CustomObject>
    <label>Order Commitment</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Order Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Commitment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Commitments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pending_Targets__c/Pending_Targets__c.object-meta.xml
<CustomObject>
    <label>Pending Targets</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Pending Targets Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pending_Targets__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pending_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pending_Targets__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Pending Targets</relationshipLabel>
    <relationshipName>Pending_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pending_Targets__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/SPM_Stats__c.object-meta.xml
<CustomObject>
    <label>SPM Stats</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>SPM Stats Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPM Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPM_Stats__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SPM_Stats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Target_Config__c.field-meta.xml
<CustomField>
    <fullName>Target_Config__c</fullName>
    <label>Target Config</label>
    <referenceTo>Target_Config__c</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/Target_Config__c.object-meta.xml
<CustomObject>
    <label>Target Config</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>TC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Config__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Configs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Target Configs</relationshipLabel>
    <relationshipName>BU_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDD</fullName>
            </value>
            <value>
                <fullName>BDM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <formula>BDM__r.FirstName +&quot; &quot; +  BDM__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Overall_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Overall_Actuals__c</fullName>
    <label>Overall Actuals</label>
    <summarizedField>SPM_Stats__c.Actual_Amount__c</summarizedField>
    <summaryForeignKey>SPM_Stats__c.Target_Config__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Sub_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sub_Channel__c</fullName>
    <label>Sub-Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Variance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Variance_Amount__c</fullName>
    <formula>Target__c - Overall_Actuals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/Target_Distribution__c.object-meta.xml
<CustomObject>
    <label>Target Distribution</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>TD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Distribution__c/fields/Allocated_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Percentage__c</fullName>
    <label>Allocated Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDD_Target_Distribustions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDM_Target_Distribustions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/Overall_Target__c.field-meta.xml
<CustomField>
    <fullName>Overall_Target__c</fullName>
    <label>Overall Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Target_Distribution__c/fields/Sub_channel__c.field-meta.xml
<CustomField>
    <fullName>Sub_channel__c</fullName>
    <label>Sub channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DTCController.cls
public class DTCController {
    @AuraEnabled(cacheable=true)
    public static List<Hierarchy_Config__c> getUserInfo(Id currentUser) {
        return [SELECT ID, Name, User__c, User__r.Name, Role__c, Manager__c FROM Hierarchy_Config__c WHERE User__c =: currentUser];
    }
    
    @AuraEnabled
    public static Map<String, Object> getDTCStats(String selYear) {
        String prevYear = 'FY-'+String.valueOf(Integer.valueOf(selYear.substring(3)) - 1);
        Map<String, Decimal> currTypeMap = new Map<String, Decimal>(); 
        Map<Id,Id> AccountMap = new map<Id,Id>();
        
        for (Account acc : [Select id,ownerId from account where XC_Channel__c = 'DTC']){
            AccountMap.put(acc.ownerId,acc.id);
        }
        
        for(CurrencyType currType : [SELECT Id,IsoCode, ConversionRate FROM CurrencyType]) {
            currTypeMap.put(currType.IsoCode, currType.ConversionRate);
        }
        
        AggregateResult agrResult = [SELECT CurrencyIsoCode,SUM(Target__c) totalAmount FROM Target_Config__c WHERE Financial_Year__c =: selYear AND account__r.XC_Channel__c = 'DTC' 
                                     GROUP BY CurrencyIsoCode]; // BDD__c =: UserInfo.getUserId()
        system.debug('agrResult'+ agrResult);
        String currencyIsoCode = (String)agrResult.get('CurrencyISOCode');
        Decimal curYearTarget = (Decimal) agrResult.get('totalAmount') * currTypeMap.get(currencyIsoCode);
        curYearTarget = curYearTarget.setScale(2, System.RoundingMode.HALF_UP);
        curYearTarget = curYearTarget != null ? curYearTarget : 0;
        
        agrResult = [SELECT SUM(Overall_Actuals__c) totalAmount FROM Target_Config__c WHERE Financial_Year__c =: selYear AND account__r.XC_Channel__c = 'DTC'];
        Decimal curYearActual = (Decimal) agrResult.get('totalAmount');
        curYearActual = curYearActual != null ? curYearActual : 0;
        
        agrResult = [SELECT currencyIsoCode,SUM(Variance_Amount__c) totalAmount FROM Target_Config__c WHERE Financial_Year__c =: selYear AND account__r.XC_Channel__c = 'DTC'
                     GROUP BY CurrencyIsoCode];
        String currencyIsoCodeVar = (String)agrResult.get('CurrencyISOCode');
        Decimal curYearVariance = (Decimal) agrResult.get('totalAmount') * currTypeMap.get(currencyIsoCodeVar);
        curYearVariance = curYearVariance.setScale(2, System.RoundingMode.HALF_UP);
        curYearVariance = curYearVariance != null ? curYearVariance : 0;
        
        agrResult = [SELECT SUM(Overall_Actuals__c) totalAmount FROM Target_Config__c WHERE Financial_Year__c =: prevYear AND account__r.XC_Channel__c = 'DTC'];
        Decimal prevYearActual = (Decimal) agrResult.get('totalAmount');
        prevYearActual = prevYearActual != null ? prevYearActual : 0;
        
        Map<String, Object> result = new Map<String, Object>();
        result.put('prevYear', prevYear);
        result.put('curYearTarget', curYearTarget);
        result.put('curYearActual', curYearActual);
        result.put('prevYearActual', prevYearActual);
        result.put('curYearVariance', curYearVariance);
        
        return result;
    }
    
    @AuraEnabled(Cacheable = true)
    public static Map<String,Object> getSubChannelStats(String financialYear, Id currentUser, Boolean isBDM) {
        
        Map<String, Object> accMap = new Map<String, Object>();
        Map<String, Decimal> currTypeMap = new Map<String, Decimal>();
        Map<String, Decimal> targetMap = new Map<String, Decimal>();
        Map<String, Decimal> actualMap = new Map<String, Decimal>();
        Map<String, Decimal> varianceMap = new Map<String, Decimal>();
        
        for(CurrencyType currType : [SELECT Id,IsoCode, ConversionRate FROM CurrencyType]) {
            currTypeMap.put(currType.IsoCode, currType.ConversionRate);   
        }        
        if(isBDM){
            
            for(Account acc : [Select Sub_Channel__c from account where XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND OwnerId = :currentUser]) {
                accMap.put(acc.Sub_Channel__c, new Map<String, Object>());
            }
            
            for(
                AggregateResult aggr : 
                [SELECT Sub_Channel__c, SUM(Target__c) FROM Target_Config__c  
                 WHERE Business_Unit__c != null AND Level__c ='BDM' AND Business_Unit__r.Available_for_Target__c = True AND 
                 BDM__c =: currentUser AND Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear
                 GROUP BY Sub_Channel__c]
            ) { 
                targetMap.put((String)aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
            }
            
            for(
                AggregateResult aggr : 
                [SELECT Sub_Channel__c, SUM(Actual_Amount__c) FROM SPM_Stats__c    
                 WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
                 BDM__c =: currentUser AND Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear
                 GROUP BY Sub_Channel__c]
            ) { 
                actualMap.put((String) aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
            }
            
            for(
                AggregateResult aggr : 
                [SELECT Sub_Channel__c,  SUM(Variance_Amount__c) FROM Target_Config__c        
                 WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
                 BDM__c =: currentUser AND  Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear
                 GROUP BY Sub_Channel__c]
            ) { 
                varianceMap.put((String) aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
            }
        }
        else{
            
            for(Account acc : [Select Sub_Channel__c from account where XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL]) {
                accMap.put(acc.Sub_Channel__c, new Map<String, Object>());
            }
            for(
                AggregateResult aggr : 
                [SELECT Sub_Channel__c, SUM(Target__c) FROM Target_Config__c  
                 WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
                 BDD__c =: currentUser AND Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear
                 GROUP BY Sub_Channel__c]
            ) { 
                targetMap.put((String)aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
            }
            
            for(
                AggregateResult aggr : 
                [SELECT Sub_Channel__c, SUM(Actual_Amount__c) FROM SPM_Stats__c    
                 WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
                 BDD__c =: currentUser AND Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear
                 GROUP BY Sub_Channel__c]
            ) { 
                actualMap.put((String) aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
            }
            
            for(
                AggregateResult aggr : 
                [SELECT Sub_Channel__c,  SUM(Variance_Amount__c) FROM Target_Config__c        
                 WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
                 BDD__c =: currentUser AND  Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear
                 GROUP BY Sub_Channel__c]
            ) { 
                varianceMap.put((String) aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
            }
        }
        
        for (String key : accMap.keySet()) {
            Map<String, Object> values = new Map<String, Object>();
            values.put('Target', targetMap.get(key) != null ? targetMap.get(key) : 0);
            values.put('Actual', actualMap.get(key) != null ? actualMap.get(key): 0);
            values.put('Variance', varianceMap.get(key) != null ? varianceMap.get(key): 0);
            
            accMap.put(key, values);                    
        }
        
        return accMap;                
    }
    
    @AuraEnabled(cacheable=true)
    public static String getBDMTargetDist(Id currentUser, String financialYear, String prevFinancialYear) {
        Decimal DBBTarget = 0;
        String currencyVal = 'USD';
        String prevFYCurrencyVal = 'USD';
        
        Map<String, BDMTargetDist> BDMTargetDistMap = new Map<String, BDMTargetDist>();
        for(Account acc : [SELECT Id, ownerId, sub_channel__c, XC_Channel__c FROM Account WHERE XC_Channel__c = 'DTC' AND sub_channel__c != null]) {
            BDMTargetDistMap.put(acc.sub_channel__c, new BDMTargetDist(acc.Id, acc.sub_channel__c,acc.XC_Channel__c, 0));
        }
        
        for(Target_Distribution__c targetDist : [SELECT Id, Allocated_Percentage__c, BDM__c, CurrencyIsoCode, Sub_channel__c FROM Target_Distribution__c WHERE Financial_Year__c =: financialYear AND BDD__c =: currentUser AND Sub_channel__c IN : BDMTargetDistMap.keySet()]) {
            currencyVal = targetDist.CurrencyIsoCode;
            BDMTargetDistMap.get(targetDist.sub_channel__c).disPercent = targetDist.Allocated_Percentage__c;
        }
        
        List<Target_Distribution__c> targetDistList = [SELECT Id, Overall_Target__c FROM Target_Distribution__c WHERE Financial_Year__c =: financialYear AND BDD__c =: currentUser AND Overall_Target__c > 0];
        
        if(!targetDistList.isEmpty()) {
            DBBTarget = targetDistList[0].Overall_Target__c;
        }
        
        List<SPM_Stats__c> actualList = [SELECT CurrencyIsoCode FROM SPM_Stats__c WHERE BDD__c =: currentUser AND Financial_Year__c =: prevFinancialYear LIMIT 1];
        if(!actualList.isEmpty()) {
            prevFYCurrencyVal = actualList[0].CurrencyIsoCode;
        }
        system.debug('BDMTargetDistMap.values()===>'+BDMTargetDistMap.values());
        return '{"currencyVal" : "'+currencyVal+'","prevFYCurrencyVal" : "'+prevFYCurrencyVal+'","BDDTarget" : "'+DBBTarget+'", "BDMList" : '+JSON.serialize(BDMTargetDistMap.values())+'}';
    }
    
    @AuraEnabled
    public static Boolean saveBDMTargetConfigs(Id currentUser, Decimal BDDTarget, String financialYear, String BDMDistData, String currencyVal, List<String> bdmList) {
        List<Target_Distribution__c> targetDistList = new List<Target_Distribution__c>();
        Map<string, Target_Distribution__c> BDMTargetDistMap = new Map<string, Target_Distribution__c>();
        
        for(BDMTargetDist BDMTargetDist : (List<BDMTargetDist>) JSON.deserialize(BDMDistData, List<BDMTargetDist>.class)) {
            BDMTargetDistMap.put(
                BDMTargetDist.Name, 
                new Target_Distribution__c(
                    Financial_Year__c = financialYear, BDD__c = currentUser, BDM__c = currentUser, sub_channel__c = BDMTargetDist.Name,
                    Allocated_Percentage__c = BDMTargetDist.disPercent, CurrencyIsoCode = currencyVal
                )
            );
        }
        
        
        for(
            Target_Distribution__c targetDist : 
            [SELECT Id, Allocated_Percentage__c, BDM__c,sub_channel__c FROM Target_Distribution__c WHERE Financial_Year__c =: financialYear AND 
             BDD__c =: currentUser  And BDM__c =: currentUser And channel__c = null]
        ) {
            if(BDMTargetDistMap.containsKey(targetDist.sub_channel__c)) {
                BDMTargetDistMap.get(targetDist.sub_channel__c).Id = targetDist.Id;
            }
        }
        
        List<Target_Distribution__c> BDDTargetDistList = [SELECT Id, Overall_Target__c FROM Target_Distribution__c WHERE Financial_Year__c =: financialYear AND BDD__c =: currentUser AND BDD__c =: currentUser And Overall_Target__c != null And channel__c = 'DTC'];
        if(!BDDTargetDistList.isEmpty()) {
            BDDTargetDistList[0].Overall_Target__c = BDDTarget;
            BDDTargetDistList[0].CurrencyIsoCode = currencyVal;
            targetDistList.add(BDDTargetDistList[0]);
        }
        
        else {
            targetDistList.add(new Target_Distribution__c(Financial_Year__c =financialYear , BDD__c=currentUser,BDM__c=currentUser, Overall_Target__c=BDDTarget,CurrencyIsoCode = currencyVal,channel__c = 'DTC'));
        }
        
        if(!BDMTargetDistMap.keyset().isEmpty()) {
            system.debug('BDMTargetDistMap==>'+BDMTargetDistMap);
            targetDistList.addAll(BDMTargetDistMap.values());
        }
        
        if(!targetDistList.isEmpty()) {
            upsert targetDistList;
            updateBDMTargets(currentUser, financialYear, BDDTarget, BDMTargetDistMap, currencyVal);
            //if(!Test.isRunningTest()){
            // UpdateSubchannelBatch myBatch = new UpdateSubchannelBatch(currentUser, financialYear, BDDTarget, null, currencyVal,bdmList);
            //Database.executeBatch(myBatch, 1);
            //}
            return true;
        }
        return false;
    }
    
    public static void updateBDMTargets(Id currentUser, String financialYear, Decimal BDDTarget, Map<String, Target_Distribution__c> BDMTargetDistMap, String currencyVal) {
        Map<String, Decimal> BDMActualsMap = new Map<String, Decimal>();
        Map<String, Decimal> currTypeMap = new Map<String, Decimal>();
        Map<Id, Decimal> missingBDMActualsMap = new Map<Id, Decimal>();
        Map<String, Target_Config__c> targetMap = new Map<String, Target_Config__c>();
        Map<String, Order_Commitment__c> orderCommitMap = new Map<String, Order_Commitment__c>();
        Map<String, Pending_Targets__c> pendingJobMap = new Map<String, Pending_Targets__c>();
        
        String prevYear = 'FY-'+String.valueOf(Integer.valueOf(financialYear.substring(3)) - 1);
        
        for(CurrencyType currType : [SELECT Id,IsoCode, ConversionRate FROM CurrencyType]) {
            currTypeMap.put(currType.IsoCode, currType.ConversionRate);
        }
        
        for(
            AggregateResult aggr : 
            [SELECT sub_channel__c, SUM(Actual_Amount__c) totalAmount FROM SPM_Stats__c WHERE Financial_Year__c =: prevYear AND BDD__c =: currentUser AND sub_channel__c IN : BDMTargetDistMap.keySet() And Actual_Amount__c > 0 GROUP BY sub_channel__c]
        ) {
            string BDMId = (string) aggr.get('sub_channel__c');
            Decimal actualsAchieved = (Decimal) aggr.get('totalAmount') * currTypeMap.get(currencyVal);
            Decimal targetCal = BDDTarget * (BDMTargetDistMap.get(BDMId).Allocated_Percentage__c / 100);
            Decimal computeIncrease = ((targetCal - actualsAchieved) / actualsAchieved);
            BDMActualsMap.put(BDMId, computeIncrease);
            
        }
        
        for(SPM_Stats__c actual : [SELECT Id, Financial_Year__c, Month__c, Account__c, Business_Unit__c, BDD__c, BDM__c, Actual_Amount__c,sub_channel__c FROM SPM_Stats__c
                                   WHERE Financial_Year__c =: prevYear AND BDD__c =: currentUser AND sub_channel__c IN : BDMActualsMap.keySet() AND BDM__c =: currentUser ])
        { 
            Decimal finalTarget = (BDMActualsMap.get(actual.sub_channel__c) * actual.Actual_Amount__c) + actual.Actual_Amount__c;
            
            if(currTypeMap.containsKey(currencyVal)) {
                finalTarget = (BDMActualsMap.get(actual.sub_channel__c) * actual.Actual_Amount__c * currTypeMap.get(currencyVal)) + (actual.Actual_Amount__c * currTypeMap.get(currencyVal));
            }
            
            String key = financialYear + '-' + String.valueOf(actual.BDD__c).substring(0, 15) + '-' 
                + String.valueOf(actual.BDM__c).substring(0, 15) + '-' + String.valueOf(actual.Account__c).substring(0, 15) + '-' 
                + String.valueOf(actual.Business_Unit__c).substring(0, 15) + '-' 
                + actual.Month__c;
            
            if(targetMap.containsKey(key)) {
                finalTarget += targetMap.get(key).Target__c;
            }
            
            
            targetMap.put(key, new Target_Config__c(
                Financial_Year__c = financialYear, Month__c = actual.Month__c, Account__c = actual.Account__c,
                Business_Unit__c = actual.Business_Unit__c, BDD__c = actual.BDD__c, BDM__c = actual.BDM__c,sub_channel__c = actual.Sub_Channel__c,
                Target__c = finalTarget, Level__c='BDM', CurrencyIsoCode = currencyVal,Year_Stats__c = 'a2V02000000QRTPEA4'
            ));
        }
        
        
        
        if(!targetMap.keySet().isEmpty()) {
            for(Target_Config__c tConfig : [SELECT Id, Target_Key__c FROM Target_Config__c WHERE Target_Key__c IN : targetMap.keySet()]) {
                if(targetMap.containsKey(tConfig.Target_Key__c)) {
                    targetMap.get(tConfig.Target_Key__c).Id = tConfig.Id;
                }
            }
            Upsert targetMap.values();
        }
    }
    
    public class BDMTargetDist {
        @AuraEnabled
        public String userId {get; set;}
        @AuraEnabled
        public String name {get; set;}
        @AuraEnabled
        public Decimal disPercent {get; set;}
        @AuraEnabled
        public string channel {get; set;}
        
        public BDMTargetDist(Id userId, String name,string channel, Decimal disPercent) {
            this.userId = userId;
            this.name = name;
            this.disPercent = disPercent;
            this.channel = channel;
        }
    }
    
    @AuraEnabled(Cacheable = true)
    public static Map<String, Object> getBDMstats(String selYear) {
        
        String currencyVal = 'USD';
        Decimal targetAchieved = 0;
        Map<Id,Id> AccountMap = new map<Id,Id>();
        
        for (Account acc : [Select id,ownerId from account where XC_Channel__c = 'DTC' and sub_channel__c != null]){
            AccountMap.put(acc.ownerId,acc.id);
        }
        
        AggregateResult agrResult = [SELECT SUm(Target__c) totalAmount FROM Target_Config__c WHERE Financial_Year__c =: selYear AND BDM__c =: UserInfo.getUserId() AND Account__r.XC_Channel__c = 'DTC' AND Account__r.XC_AccountStatus__c ='Active' AND Sub_Channel__c != null];
        Decimal curYearTarget = (Decimal) agrResult.get('totalAmount');
        curYearTarget = curYearTarget != null ? curYearTarget : 0;
        
        agrResult = [SELECT SUM(Overall_Actuals__c) totalAmount FROM Target_Config__c WHERE  Financial_Year__c =: selYear AND BDM__c =: UserInfo.getUserId() AND Account__r.XC_Channel__c = 'DTC' AND Account__r.XC_AccountStatus__c ='Active' AND Sub_Channel__c != null];
        Decimal curYearActual = (Decimal) agrResult.get('totalAmount');
        curYearActual = curYearActual != null ? curYearActual : 0;
        
        agrResult = [SELECT SUM(Variance_Amount__c) totalAmount FROM Target_Config__c WHERE  Financial_Year__c =: selYear AND BDM__c =: UserInfo.getUserId() AND Account__r.XC_Channel__c = 'DTC' AND Account__r.XC_AccountStatus__c ='Active' AND Sub_Channel__c != null];
        Decimal curYearvariance = (Decimal) agrResult.get('totalAmount');
        curYearvariance = curYearvariance != null ? curYearvariance : 0;
        
        agrResult = [SELECT COUNT(OwnerId) totalAmount FROM Account WHERE OwnerId =: UserInfo.getUserId() AND Authorized_Business_Units__c != NULL AND ParentId = NULL AND XC_AccountStatus__c = 'Active'];
        Decimal totalAccount = (Decimal) agrResult.get('totalAmount');
        totalAccount = totalAccount != null ? totalAccount : 0;
        
        if (curYearTarget != 0) {
            targetAchieved = (curYearActual/curYearTarget)*100;
            targetAchieved = targetAchieved != null ? targetAchieved : 0;
        }
        
        for(Target_Config__c tarConfig : [SELECT CurrencyIsoCode FROM Target_Config__c
                                          WHERE Financial_Year__c =: selYear AND BDM__c =: UserInfo.getUserId()]){
                                              currencyVal = tarConfig.CurrencyIsoCode;      
                                          }
        Map<String, Object> result = new Map<String, Object>();
        
        result.put('curYearTarget', curYearTarget);
        result.put('curYearActual', curYearActual);
        result.put('curYearVariance', curYearvariance);
        result.put('totalAccount', totalAccount);
        result.put('targetAchieved', targetAchieved);  
        result.put('currencyVal', currencyVal);
        return result;
    }
    
    @AuraEnabled(Cacheable = true)
    public static Map<String,Object> getSubChannelBDMStats(String financialYear, Id currentUser) {
        
        Map<String, Object> accMap = new Map<String, Object>();
        Map<String, Decimal> currTypeMap = new Map<String, Decimal>();
        Map<String, Decimal> targetMap = new Map<String, Decimal>();
        Map<String, Decimal> actualMap = new Map<String, Decimal>();
        Map<String, Decimal> varianceMap = new Map<String, Decimal>();
        Map<Id,Id> AccountMap = new map<Id,Id>();
        
        for(CurrencyType currType : [SELECT Id,IsoCode, ConversionRate FROM CurrencyType]) {
            currTypeMap.put(currType.IsoCode, currType.ConversionRate);   
        }
        
        for(Account acc : [Select Sub_Channel__c from account where XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL]) {
            accMap.put(acc.Sub_Channel__c, new Map<String, Object>());
        }
        
        for(
            AggregateResult aggr : 
            [SELECT Sub_Channel__c, SUM(Target__c) FROM Target_Config__c  
             WHERE Business_Unit__c != null AND Level__c ='BDM' AND Business_Unit__r.Available_for_Target__c = True AND 
             BDD__c =: currentUser AND Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear AND account__c = : AccountMap.get(UserInfo.getUserId())
             GROUP BY Sub_Channel__c]
        ) { 
            targetMap.put((String)aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
        }
        
        for(
            AggregateResult aggr : 
            [SELECT Sub_Channel__c, SUM(Actual_Amount__c) FROM SPM_Stats__c    
             WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
             BDD__c =: currentUser AND Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear AND account__c = : AccountMap.get(UserInfo.getUserId())
             GROUP BY Sub_Channel__c]
        ) { 
            actualMap.put((String) aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
        }
        
        for(
            AggregateResult aggr : 
            [SELECT Sub_Channel__c,  SUM(Variance_Amount__c) FROM Target_Config__c        
             WHERE Business_Unit__c != null AND Business_Unit__r.Available_for_Target__c = True AND 
             BDD__c =: currentUser AND  Account__r.XC_Channel__c = 'DTC' AND Sub_Channel__c != NULL AND Financial_Year__c =: financialYear AND account__c = : AccountMap.get(UserInfo.getUserId())
             GROUP BY Sub_Channel__c]
        ) { 
            varianceMap.put((String) aggr.get('Sub_Channel__c'),(Decimal) aggr.get('expr0')!= null ? (Decimal) aggr.get('expr0') : 0);
        }
        
        for (String key : accMap.keySet()) {
            Map<String, Object> values = new Map<String, Object>();
            values.put('Target', targetMap.get(key) != null ? targetMap.get(key) : 0);
            values.put('Actual', actualMap.get(key) != null ? actualMap.get(key): 0);
            values.put('Variance', varianceMap.get(key) != null ? varianceMap.get(key): 0);
            
            accMap.put(key, values);                    
        }
        return accMap;                
    }
    
    
}