force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Unit__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Hierarchy_Config__c/Hierarchy_Config__c.object-meta.xml
<CustomObject>
    <label>Hierarchy Config</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>HC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hierarchy Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hierarchy_Config__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDD_Hierarchy_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Config__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDM</fullName>
            </value>
            <value>
                <fullName>BDD</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>DTC BDD</fullName>
            </value>
            <value>
                <fullName>DTC BDM</fullName>
            </value>
            <value>
                <fullName>Sales Person</fullName>
                <isActive>false</isActive>
                <label>Sales Person</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hierarchy_Config__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDM_Hierarchy_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/SPM_Stats__c.object-meta.xml
<CustomObject>
    <label>SPM Stats</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>SPM Stats Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPM Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPM_Stats__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SPM_Stats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>Feb</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>Mar</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>Apr</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>Jul</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>Aug</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>Sep</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>Oct</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>Nov</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>Dec</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Open_Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Open_Actual_Amount__c</fullName>
    <label>Open Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Target_Config__c.field-meta.xml
<CustomField>
    <fullName>Target_Config__c</fullName>
    <label>Target Config</label>
    <referenceTo>Target_Config__c</referenceTo>
    <relationshipLabel>SPM Stats</relationshipLabel>
    <relationshipName>SPM_Stats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPM_Stats__c/fields/Target_Key__c.field-meta.xml
<CustomField>
    <fullName>Target_Key__c</fullName>
    <formula>TEXT(Financial_Year__c) + &apos;-&apos; + BDD__c + &apos;-&apos; + BDM__c + &apos;-&apos; + Account__c + &apos;-&apos; + Business_Unit__c + &apos;-&apos; + TEXT(Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/Target_Config__c.object-meta.xml
<CustomObject>
    <label>Target Config</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>TC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Config__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/BDD__c.field-meta.xml
<CustomField>
    <fullName>BDD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDD</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Configs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Target Configs</relationshipLabel>
    <relationshipName>BU_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <formula>BDM__r.FirstName +&quot; &quot; +  BDM__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Target_Config__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Target_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderItemController.cls
public class OrderItemController {
    public static void createActuals(Map<Id, OrderItem> newOrderMap) {
        try {
            List<SPM_Stats__c> actualList = new List<SPM_Stats__c>();
            Map<String, Id> buMap = new Map<String, Id>();
            Map<Id, Id> configMap = new Map<Id, Id>();
            Map<String, Id> tConfigMap = new Map<String, Id>();
            
            for(Business_Unit__c bu : [SELECT Id, Unique_Name__c FROM Business_Unit__c]) {
                buMap.put(bu.Unique_Name__c, bu.Id);
            }
            
            for(Hierarchy_Config__c hConfig : [SELECT Id, User__c, Manager__c FROM Hierarchy_Config__c WHERE Role__c = 'BDM' AND Manager__c != null]) {
                configMap.put(hConfig.User__c, hConfig.Manager__c);
            }
            
            for(
                OrderItem ordItem : 
                [SELECT Id, OrderId, Order.OrderedDate, Order.AccountId, Order.Account.OwnerId,Order.XC_Order_Status__c, Product2Id, Product2.Business_Unit__c, TotalPrice 
                 FROM OrderItem WHERE Id IN :newOrderMap.keySet() AND Order.OrderedDate != null AND Order.XC_Order_Status__c != 'Canceled']
            ) {
                if(ordItem.Order == null || ordItem.Order.OrderedDate == null || ordItem.Order.Account == null || ordItem.Order.Account.OwnerId == null || ordItem.Product2 == null || ordItem.Product2.Business_Unit__c == null) {
                    continue;
                }
                
                String monthName = getMonthName(ordItem.Order.OrderedDate);
                String key = 'FY-' + String.valueOf(ordItem.Order.OrderedDate.year()).substring(2, 4)  
                    + '-' + String.valueOf(configMap.get(ordItem.Order.Account.OwnerId)).substring(0, 15) + '-' + String.valueOf(ordItem.Order.Account.OwnerId).substring(0, 15) 
                    + '-' + String.valueOf(ordItem.Order.AccountId).substring(0, 15) + '-' + String.valueOf(buMap.get(ordItem.Product2.Business_Unit__c)).substring(0, 15) 
                    + '-' + monthName;
                
                Id tConfigId = tConfigMap.get(key);
                
                if(tConfigId == null) {
                    Target_Config__c tConfig = [SELECT Id FROM Target_Config__c WHERE Target_Key__c = :key LIMIT 1];
                    if(tConfig != null) {
                        tConfigMap.put(key, tConfig.Id);
                        tConfigId = tConfig.Id;
                    }
                }
                
                SPM_Stats__c actual = new SPM_Stats__c(
                    Order__c = ordItem.OrderId,
                    Order_Product__c = ordItem.Id,
                    Product__c = ordItem.Product2Id,
                    Business_Unit__c = buMap.get(ordItem.Product2.Business_Unit__c),
                    Account__c = ordItem.Order.AccountId,
                    Financial_Year__c = 'FY-' + String.valueOf(ordItem.Order.OrderedDate.year()).substring(2, 4),
                    Month__c = monthName,
                    BDM__c = ordItem.Order.Account.OwnerId,
                    BDD__c = configMap.get(ordItem.Order.Account.OwnerId),
                    Target_Config__c = tConfigId,
                    currencyISOcode = 'USD'   
                );
                
                if(ordItem.Order.XC_Order_Status__c == 'Invoiced'){
                    actual.Actual_Amount__c = ordItem.TotalPrice;
                    actualList.add(actual);
                }
                else{
                    actual.Open_Actual_Amount__c = ordItem.TotalPrice;
                    actualList.add(actual);
                }   
            }
            
            if(!actualList.isEmpty()) {
                insert actualList;
            }
        } catch(Exception e) {
            System.debug('Error occurred: ' + e.getMessage());
        }
    }
    
    public static void updateActualsOnOrderItemUpdate(Map<Id, OrderItem> newOrderItemMap, Map<Id, OrderItem> oldOrderItemMap) {     
        try {
            Set<Id> orderItemIds = new Set<Id>();
            List<SPM_Stats__c> statsList = new List<SPM_Stats__c>();
            List<SPM_Stats__c> actualListToUpdate = new List<SPM_Stats__c>();
            Map<Id,SPM_Stats__c > statsOrderItemMap = new Map<Id, SPM_Stats__c>();
            
            for (OrderItem updatedOrderItem : newOrderItemMap.values()) {
                OrderItem oldOrderItem = oldOrderItemMap.get(updatedOrderItem.Id);
                if ((updatedOrderItem.TotalPrice != oldOrderItem.TotalPrice) || (updatedOrderItem.Order.XC_Order_Status__c != oldOrderItem.Order.XC_Order_Status__c)) {
                    orderItemIds.add(updatedOrderItem.Id);                    
                }
            } 
			statsList = [SELECT Id, Order_Product__c,Order__r.XC_Order_Status__c,Actual_Amount__c,Open_Actual_Amount__c FROM SPM_Stats__c 
                         WHERE Order_Product__c IN :orderItemIds];
            for (SPM_Stats__c stat : statsList) {
                statsOrderItemMap.put(stat.Order_Product__c, stat);
            }
            for (OrderItem updatedOrderItem : newOrderItemMap.values()) {
                SPM_Stats__c actual = statsOrderItemMap.get(updatedOrderItem.Id);
                if (actual != null) {
                    if (actual.Order__r.XC_Order_Status__c == 'Invoiced') {
                        actual.Actual_Amount__c = updatedOrderItem.TotalPrice;
                        actual.Open_Actual_Amount__c = 0;
                        actualListToUpdate.add(actual);   
                    } else {
                        actual.Actual_Amount__c = 0;
                        actual.Open_Actual_Amount__c = updatedOrderItem.TotalPrice;
                        actualListToUpdate.add(actual);
                    }
                }
            }
            if (!actualListToUpdate.isEmpty()) {
                update actualListToUpdate;
            }
        } catch (Exception e) {
            System.debug('Error occurred: ' + e.getMessage());
        }
    }
   
    public static String getMonthName(Datetime datetimeValue) {
        Date dateValue = datetimeValue.date();
        String orderedDateStr = String.valueOf(dateValue);
        String monthNumber = orderedDateStr.substring(5, 7);
        Integer monthValue = Integer.valueOf(monthNumber);
        String[] monthNames = new String[] { 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'};
            if (monthValue >= 1 && monthValue <= 12) {
                return monthNames[monthValue - 1];
            }
        return '';
    }   
}