force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Commitment__c/Order_Commitment__c.object-meta.xml
<CustomObject>
    <label>Order Commitment</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Order Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Commitment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Commitments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <formula>TEXT(Financial_Year__c) + &apos;-&apos; + BDM__c + &apos;-&apos; + Account__c + &apos;-&apos; + Business_Unit__c + &apos;-&apos; +  Product__c + &apos;-&apos; + TEXT(Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Commitment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Commitments</relationshipLabel>
    <relationshipName>Order_Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/Target_Commit_Stats__c.object-meta.xml
<CustomObject>
    <label>Target Commit Stats</label>
    <nameField>
        <displayFormat>TCS-{0000}</displayFormat>
        <label>Target Commit Stats Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Commit Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Target Commit Stats</relationshipLabel>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Apr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aug</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BDM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Target Commit Stats</relationshipLabel>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Check_Error__c.field-meta.xml
<CustomField>
    <fullName>Check_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Dec</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Feb</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/IsUpload__c.field-meta.xml
<CustomField>
    <fullName>IsUpload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jan</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jul</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Jun</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <formula>TEXT(Financial_Year__c ) + &apos;-&apos; + BDM__c + &apos;-&apos; + Account__c + &apos;-&apos; +  Business_Unit__c + &apos;-&apos; + Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <defaultValue>0</defaultValue>
    <label>May</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Non_Available_Product__c.field-meta.xml
<CustomField>
    <fullName>Non_Available_Product__c</fullName>
    <formula>TODAY() &lt;  Product__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Available Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nov</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Oct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Target Commit Stats</relationshipLabel>
    <relationshipName>Target_Commit_Stats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target_Commit_Stats__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default Data</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcessTargetCommitRecords.cls
public class ProcessTargetCommitRecords implements Database.Batchable<sObject>, Database.Stateful {
    
    Map<Id, String> BDMID_MAP = new Map<Id, String>();
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String dynamicQuery = 'SELECT Id, Account__c, BDM__c, BDM__r.Email, Product__c,Product__r.Start_Date__c, Business_Unit__c, Financial_Year__c, Non_Available_Product__c, ' + 
            'Key__c, Status__c, Unit_Price__c, Jan__c, Feb__c, Mar__c, Apr__c, May__c, Jun__c, Jul__c, Aug__c, Sep__c,Check_Error__c, ' + 
            'Oct__c, Nov__c, Dec__c FROM Target_Commit_Stats__c WHERE Status__c = \'Pending\' AND IsUpload__c = True';
        return Database.getQueryLocator(dynamicQuery);
    }
    
    public void execute(Database.BatchableContext bc, List<Target_Commit_Stats__c> scope) {
       Map<String, Integer> monthMap = new Map<String, Integer>{
            'Jan' => 1, 'Feb' => 2, 'Mar' => 3, 'Apr' => 4, 'May' => 5, 'Jun' => 6,
            'Jul' => 7, 'Aug' => 8, 'Sep' => 9, 'Oct' => 10, 'Nov' => 11, 'Dec' => 12
        };
                    
        List<Order_Commitment__c> ordCommitList = new List<Order_Commitment__c>();
        Map<String, Target_Commit_Stats__c> keyMap = new Map<String, Target_Commit_Stats__c>();
        List<String> months = new List<String>{'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'};
        Integer currentMonth = System.today().month();
        Integer currentDay = System.today().day();
        
        for(Target_Commit_Stats__c tcs : scope) {
            for(String month : months) {
                String numericPart = tcs.Financial_Year__c.substring(3);
                Integer baseYear = 2000; 
                Integer fullYear = baseYear + Integer.valueOf(numericPart);
                
                if (monthMap.get(month) > 3) {
                    fullYear--;
                }
                
                if(monthMap.get(month) < currentMonth && System.today().year() == fullYear) {
                    continue;
                }
                
                Date itemStartDate = Date.newInstance(fullYear, monthMap.get(month), 1);
                
                if(tcs.Product__r.Start_Date__c != null){
                    if (
                        currentMonth == monthMap.get(month) && currentDay >= tcs.Product__r.Start_Date__c.day() && 
                        itemStartDate.month() == tcs.Product__r.Start_Date__c.month() && 
                        itemStartDate.year() == tcs.Product__r.Start_Date__c.year()
                    ) {
                        itemStartDate = tcs.Product__r.Start_Date__c;
                    }
                    
                    if(itemStartDate < tcs.Product__r.Start_Date__c) {
                        tcs.Check_Error__c = true;
                        BDMID_MAP.put(tcs.BDM__c, tcs.BDM__r.Email);
                        continue;
                    }
                }
                keyMap.put(tcs.key__c+'-'+month, tcs);
            }
        }
        
        Update scope;
        
        for(Order_Commitment__c existOrdCommitment : [SELECT Id, Key__c, Month__c, Quantity__c FROM Order_Commitment__c where key__c IN : keyMap.keySet()]){
            if(keyMap.containsKey(existOrdCommitment.Key__c)){
                Sobject sObj = keyMap.get(existOrdCommitment.Key__c);
                existOrdCommitment.Quantity__c = (Decimal) sObj.get(existOrdCommitment.Month__c+'__c');
                keyMap.remove(existOrdCommitment.Key__c);
                ordCommitList.add(existOrdCommitment);
            }
        }
        
        for(String key : keyMap.keySet()) {
            Sobject sObj = keyMap.get(key);
            Order_Commitment__c ord = new Order_Commitment__c();
            ord.Account__c = (Id) sObj.get('Account__c');
            ord.BDM__c = (Id) sObj.get('BDM__c');
            ord.Product__c = (Id) sObj.get('Product__c');
            ord.Business_Unit__c = (Id) sObj.get('Business_Unit__c');
            ord.Unit_Price__c = (Decimal) sObj.get('Unit_Price__c');
            ord.Financial_Year__c = (String) sObj.get('Financial_Year__c');
            
            String month = key.subString(key.length() - 3);
            ord.Month__c = month;
            ord.Quantity__c = (Decimal) sObj.get(month+'__c');
            
            ordCommitList.add(ord);
        }
        
        if (!ordCommitList.isEmpty()) {
            upsert ordCommitList;
        }
        
        for (Target_Commit_Stats__c tcStats : scope) {
            tcStats.Status__c = 'Completed';
        }
        update scope;
    }
    
    
    
    public void finish(Database.BatchableContext bc) {
        Set<Id> remainingBDMIds = new Set<Id>(BDMID_MAP.keySet());
        Map<Id, String> bdmIdToNameMap = new Map<Id, String>();
        
        if(!BDMID_MAP.keySet().isEmpty()) {
            for (User bdmUser : [SELECT Id, Name FROM User WHERE Id IN :remainingBDMIds]) {
                bdmIdToNameMap.put(bdmUser.Id, bdmUser.Name);
            }
            
            for(
                AggregateResult tcs : [SELECT COUNT(Id) bdmCount,BDM__c,Status__c FROM Target_Commit_Stats__c WHERE BDM__c IN : BDMID_MAP.keySet()
                                       AND Status__c = 'Pending' GROUP BY BDM__c, Status__c])
            {
                BDMID_MAP.remove((Id) tcs.get('BDM__c'));
            }
        }
        
        if(!BDMID_MAP.keySet().isEmpty()) {
            List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
            EmailTemplate et = [SELECT Id, subject, HtmlValue FROM EmailTemplate WHERE DeveloperName =: 'Non_available_SKU_Template'];            
            
            for(String email : BDMID_MAP.values()) {
                
                if(et != null){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    String[] toAddresses = new String[] { email };
                        String body = et.HtmlValue;
                    
                    for (Id bdmId : remainingBDMIds) {
                        String bdmName = bdmIdToNameMap.get(bdmId);
                        body = body.replaceAll('\\{!Target_Commit_Stats__c.BDM__c\\}', bdmName);
                        mail.setToAddresses(toAddresses);
                        mail.setTemplateId(et.Id); 
                        mail.setSubject(et.subject);
                        mail.setHTMLBody(body);
                    }
                    
                    mailList.add(mail);
                }
            }
            
            Messaging.sendEmail(mailList);
        }    
    }
    
}